; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ${PROJECT_DIR}/boards_custom

[env:MagicBandHub]
platform = espressif32@6.7.0
board = waveshare_esp32s3_touch_lcd_128
framework = arduino
board_build.partitions = full_16mb_app.csv
lib_extra_dirs = 
	~/Documents/Arduino/libraries
lib_deps = 
	WiFi@2.0.0
	lvgl@8.3.11
build_flags = 
	-DLV_CONF_INCLUDE_SIMPLE
	-I src
build_type = debug
monitor_speed = 115200
