// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void fn_start_registration(lv_event_t * e);
void fn_save_band(lv_event_t * e);
void fn_prepare_edit_panel(lv_event_t * e);
void fn_delete_selected_band(lv_event_t * e);
void fn_toggle_wifi(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
