// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#include "ui.h"

lv_obj_t *uic_StatusLabel;
lv_obj_t *uic_Hotspot;
lv_obj_t *ui_Hotspot = NULL;lv_obj_t *ui_HotspotToggle = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_StatusLabel = NULL;
// event funtions
void ui_event_Hotspot( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Scanner, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Scanner_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ManageBands, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ManageBands_screen_init);
}
}

void ui_event_HotspotToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      fn_toggle_wifi( e );
}
}

// build funtions

void ui_Hotspot_screen_init(void)
{
ui_Hotspot = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Hotspot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HotspotToggle = lv_btn_create(ui_Hotspot);
lv_obj_set_width( ui_HotspotToggle, 170);
lv_obj_set_height( ui_HotspotToggle, 50);
lv_obj_set_align( ui_HotspotToggle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HotspotToggle, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HotspotToggle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_HotspotToggle);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Toggle Wifi");

ui_StatusLabel = lv_label_create(ui_Hotspot);
lv_obj_set_width( ui_StatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StatusLabel, -2 );
lv_obj_set_y( ui_StatusLabel, -52 );
lv_obj_set_align( ui_StatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StatusLabel,"Tap Bellow to Set Up Wifi");

lv_obj_add_event_cb(ui_HotspotToggle, ui_event_HotspotToggle, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Hotspot, ui_event_Hotspot, LV_EVENT_ALL, NULL);
uic_Hotspot = ui_Hotspot;
uic_StatusLabel = ui_StatusLabel;

}

void ui_Hotspot_screen_destroy(void)
{
   if (ui_Hotspot) lv_obj_del(ui_Hotspot);

// NULL screen variables
uic_Hotspot= NULL;
ui_Hotspot= NULL;
ui_HotspotToggle= NULL;
ui_Label9= NULL;
uic_StatusLabel= NULL;
ui_StatusLabel= NULL;

}
