// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#ifndef UI_HOTSPOT_H
#define UI_HOTSPOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Hotspot
extern void ui_Hotspot_screen_init(void);
extern void ui_Hotspot_screen_destroy(void);
extern void ui_event_Hotspot( lv_event_t * e);
extern lv_obj_t *ui_Hotspot;
extern void ui_event_HotspotToggle( lv_event_t * e);
extern lv_obj_t *ui_HotspotToggle;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_StatusLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Hotspot;
extern lv_obj_t *uic_StatusLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

