// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#ifndef UI_MANAGEBANDS_H
#define UI_MANAGEBANDS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ManageBands
extern void ui_ManageBands_screen_init(void);
extern void ui_ManageBands_screen_destroy(void);
extern void ui_event_ManageBands( lv_event_t * e);
extern lv_obj_t *ui_ManageBands;
extern lv_obj_t *ui_BandListPnl;
extern lv_obj_t *ui_BandRoller;
extern void ui_event_BtnOpenEdit( lv_event_t * e);
extern lv_obj_t *ui_BtnOpenEdit;
extern lv_obj_t *ui_BandEditBtn;
extern lv_obj_t *ui_EditPanel;
extern void ui_event_BtnDeleteBand( lv_event_t * e);
extern lv_obj_t *ui_BtnDeleteBand;
extern lv_obj_t *ui_Label5;
extern void ui_event_BtnBackToList( lv_event_t * e);
extern lv_obj_t *ui_BtnBackToList;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_EditNameLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ManageBands;
extern lv_obj_t *uic_BandListPnl;
extern lv_obj_t *uic_BandRoller;
extern lv_obj_t *uic_BtnOpenEdit;
extern lv_obj_t *uic_BandEditBtn;
extern lv_obj_t *uic_EditPanel;
extern lv_obj_t *uic_BtnDeleteBand;
extern lv_obj_t *uic_BtnBackToList;
extern lv_obj_t *uic_EditNameLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

