// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#include "ui.h"

lv_obj_t *uic_EditNameLabel;
lv_obj_t *uic_BtnBackToList;
lv_obj_t *uic_BtnDeleteBand;
lv_obj_t *uic_EditPanel;
lv_obj_t *uic_BandEditBtn;
lv_obj_t *uic_BtnOpenEdit;
lv_obj_t *uic_BandRoller;
lv_obj_t *uic_BandListPnl;
lv_obj_t *uic_ManageBands;
lv_obj_t *ui_ManageBands = NULL;lv_obj_t *ui_BandListPnl = NULL;lv_obj_t *ui_BandRoller = NULL;lv_obj_t *ui_BtnOpenEdit = NULL;lv_obj_t *ui_BandEditBtn = NULL;lv_obj_t *ui_EditPanel = NULL;lv_obj_t *ui_BtnDeleteBand = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_BtnBackToList = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_EditNameLabel = NULL;
// event funtions
void ui_event_ManageBands( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Scanner, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Scanner_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Hotspot, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Hotspot_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ManageBands, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ManageBands_screen_init);
}
}

void ui_event_BtnOpenEdit( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      fn_prepare_edit_panel( e );
      _ui_flag_modify( ui_EditPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_BtnDeleteBand( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      fn_delete_selected_band( e );
}
}

void ui_event_BtnBackToList( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_EditPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_ManageBands_screen_init(void)
{
ui_ManageBands = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ManageBands, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ManageBands, lv_color_hex(0xF9F6DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ManageBands, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ManageBands, &ui_img_white_starsbackground_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_BandListPnl = lv_obj_create(ui_ManageBands);
lv_obj_set_width( ui_BandListPnl, 240);
lv_obj_set_height( ui_BandListPnl, 240);
lv_obj_set_align( ui_BandListPnl, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BandListPnl, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BandListPnl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BandListPnl, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BandRoller = lv_roller_create(ui_BandListPnl);
lv_roller_set_options( ui_BandRoller, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_INFINITE );
lv_obj_set_height( ui_BandRoller, 129);
lv_obj_set_width( ui_BandRoller, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_BandRoller, -3 );
lv_obj_set_y( ui_BandRoller, -31 );
lv_obj_set_align( ui_BandRoller, LV_ALIGN_CENTER );
lv_obj_set_style_text_align(ui_BandRoller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnOpenEdit = lv_btn_create(ui_BandListPnl);
lv_obj_set_width( ui_BtnOpenEdit, 100);
lv_obj_set_height( ui_BtnOpenEdit, 40);
lv_obj_set_x( ui_BtnOpenEdit, 0 );
lv_obj_set_y( ui_BtnOpenEdit, 76 );
lv_obj_set_align( ui_BtnOpenEdit, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnOpenEdit, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnOpenEdit, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BtnOpenEdit, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BtnOpenEdit, lv_color_hex(0x3677A3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnOpenEdit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BandEditBtn = lv_label_create(ui_BtnOpenEdit);
lv_obj_set_width( ui_BandEditBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BandEditBtn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BandEditBtn, LV_ALIGN_CENTER );
lv_label_set_text(ui_BandEditBtn,"EDIT");

ui_EditPanel = lv_obj_create(ui_ManageBands);
lv_obj_set_width( ui_EditPanel, 240);
lv_obj_set_height( ui_EditPanel, 240);
lv_obj_set_align( ui_EditPanel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_EditPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_EditPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(ui_EditPanel, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EditPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_EditPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_BtnDeleteBand = lv_btn_create(ui_EditPanel);
lv_obj_set_width( ui_BtnDeleteBand, 100);
lv_obj_set_height( ui_BtnDeleteBand, 50);
lv_obj_set_align( ui_BtnDeleteBand, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnDeleteBand, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnDeleteBand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnDeleteBand, lv_color_hex(0x865151), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnDeleteBand, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_BtnDeleteBand);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Delete Band");

ui_BtnBackToList = lv_btn_create(ui_EditPanel);
lv_obj_set_width( ui_BtnBackToList, 100);
lv_obj_set_height( ui_BtnBackToList, 50);
lv_obj_set_x( ui_BtnBackToList, 0 );
lv_obj_set_y( ui_BtnBackToList, 62 );
lv_obj_set_align( ui_BtnBackToList, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnBackToList, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnBackToList, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_BtnBackToList);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Back");

ui_EditNameLabel = lv_label_create(ui_EditPanel);
lv_obj_set_width( ui_EditNameLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_EditNameLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_EditNameLabel, -2 );
lv_obj_set_y( ui_EditNameLabel, -69 );
lv_obj_set_align( ui_EditNameLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_EditNameLabel,"BandName");

lv_obj_add_event_cb(ui_BtnOpenEdit, ui_event_BtnOpenEdit, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnDeleteBand, ui_event_BtnDeleteBand, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnBackToList, ui_event_BtnBackToList, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ManageBands, ui_event_ManageBands, LV_EVENT_ALL, NULL);
uic_ManageBands = ui_ManageBands;
uic_BandListPnl = ui_BandListPnl;
uic_BandRoller = ui_BandRoller;
uic_BtnOpenEdit = ui_BtnOpenEdit;
uic_BandEditBtn = ui_BandEditBtn;
uic_EditPanel = ui_EditPanel;
uic_BtnDeleteBand = ui_BtnDeleteBand;
uic_BtnBackToList = ui_BtnBackToList;
uic_EditNameLabel = ui_EditNameLabel;

}

void ui_ManageBands_screen_destroy(void)
{
   if (ui_ManageBands) lv_obj_del(ui_ManageBands);

// NULL screen variables
uic_ManageBands= NULL;
ui_ManageBands= NULL;
uic_BandListPnl= NULL;
ui_BandListPnl= NULL;
uic_BandRoller= NULL;
ui_BandRoller= NULL;
uic_BtnOpenEdit= NULL;
ui_BtnOpenEdit= NULL;
uic_BandEditBtn= NULL;
ui_BandEditBtn= NULL;
uic_EditPanel= NULL;
ui_EditPanel= NULL;
uic_BtnDeleteBand= NULL;
ui_BtnDeleteBand= NULL;
ui_Label5= NULL;
uic_BtnBackToList= NULL;
ui_BtnBackToList= NULL;
ui_Label6= NULL;
uic_EditNameLabel= NULL;
ui_EditNameLabel= NULL;

}
