// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#ifndef UI_RECORDSCREEN_H
#define UI_RECORDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RecordScreen
extern void ui_RecordScreen_screen_init(void);
extern void ui_RecordScreen_screen_destroy(void);
extern void ui_event_RecordScreen( lv_event_t * e);
extern lv_obj_t *ui_RecordScreen;
extern lv_obj_t *ui_ScanBandPnl1;
extern void ui_event_ScanBandBtn( lv_event_t * e);
extern lv_obj_t *ui_ScanBandBtn;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_ScanBandPnl2;
extern lv_obj_t *ui_Colorwheel2;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_ScanBandPnl3;
extern lv_obj_t *ui_BandNameTextArea;
extern lv_obj_t *ui_Keyboard1;
extern void ui_event_SaveNewBand( lv_event_t * e);
extern lv_obj_t *ui_SaveNewBand;
extern lv_obj_t *ui_Label4;
// CUSTOM VARIABLES
extern lv_obj_t *uic_RecordScreen;
extern lv_obj_t *uic_ScanBandPnl1;
extern lv_obj_t *uic_ScanBandBtn;
extern lv_obj_t *uic_ScanBandPnl2;
extern lv_obj_t *uic_ScanBandPnl3;
extern lv_obj_t *uic_BandNameTextArea;
extern lv_obj_t *uic_SaveNewBand;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

