// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#include "ui.h"

lv_obj_t *uic_SaveNewBand;
lv_obj_t *uic_BandNameTextArea;
lv_obj_t *uic_ScanBandPnl3;
lv_obj_t *uic_ScanBandPnl2;
lv_obj_t *uic_ScanBandBtn;
lv_obj_t *uic_ScanBandPnl1;
lv_obj_t *uic_RecordScreen;
lv_obj_t *ui_RecordScreen = NULL;lv_obj_t *ui_ScanBandPnl1 = NULL;lv_obj_t *ui_ScanBandBtn = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_ScanBandPnl2 = NULL;lv_obj_t *ui_Colorwheel2 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_ScanBandPnl3 = NULL;lv_obj_t *ui_BandNameTextArea = NULL;lv_obj_t *ui_Keyboard1 = NULL;lv_obj_t *ui_SaveNewBand = NULL;lv_obj_t *ui_Label4 = NULL;
// event funtions
void ui_event_RecordScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Scanner, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Scanner_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ManageBands, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ManageBands_screen_init);
}
}

void ui_event_ScanBandBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      fn_start_registration( e );
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_ScanBandPnl2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_ScanBandPnl3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_SaveNewBand( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      fn_save_band( e );
}
}

// build funtions

void ui_RecordScreen_screen_init(void)
{
ui_RecordScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_RecordScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScanBandPnl1 = lv_obj_create(ui_RecordScreen);
lv_obj_set_width( ui_ScanBandPnl1, 240);
lv_obj_set_height( ui_ScanBandPnl1, 240);
lv_obj_set_align( ui_ScanBandPnl1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScanBandPnl1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ScanBandPnl1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScanBandBtn = lv_btn_create(ui_ScanBandPnl1);
lv_obj_set_width( ui_ScanBandBtn, 100);
lv_obj_set_height( ui_ScanBandBtn, 50);
lv_obj_set_x( ui_ScanBandBtn, 1 );
lv_obj_set_y( ui_ScanBandBtn, 0 );
lv_obj_set_align( ui_ScanBandBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScanBandBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScanBandBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_ScanBandBtn);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"RECORD\nBAND");
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScanBandPnl2 = lv_obj_create(ui_RecordScreen);
lv_obj_set_width( ui_ScanBandPnl2, 240);
lv_obj_set_height( ui_ScanBandPnl2, 240);
lv_obj_set_align( ui_ScanBandPnl2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ScanBandPnl2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ScanBandPnl2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Colorwheel2 = lv_colorwheel_create(ui_ScanBandPnl2,true);
lv_obj_set_width( ui_Colorwheel2, 100);
lv_obj_set_height( ui_Colorwheel2, 100);
lv_obj_set_x( ui_Colorwheel2, -2 );
lv_obj_set_y( ui_Colorwheel2, -34 );
lv_obj_set_align( ui_Colorwheel2, LV_ALIGN_CENTER );

ui_Button2 = lv_btn_create(ui_ScanBandPnl2);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 50);
lv_obj_set_x( ui_Button2, 3 );
lv_obj_set_y( ui_Button2, 78 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Save");

ui_ScanBandPnl3 = lv_obj_create(ui_RecordScreen);
lv_obj_set_width( ui_ScanBandPnl3, 240);
lv_obj_set_height( ui_ScanBandPnl3, 240);
lv_obj_set_align( ui_ScanBandPnl3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScanBandPnl3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BandNameTextArea = lv_textarea_create(ui_ScanBandPnl3);
lv_obj_set_width( ui_BandNameTextArea, 150);
lv_obj_set_height( ui_BandNameTextArea, 36);
lv_obj_set_x( ui_BandNameTextArea, 0 );
lv_obj_set_y( ui_BandNameTextArea, -73 );
lv_obj_set_align( ui_BandNameTextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_BandNameTextArea,"Placeholder...");

ui_Keyboard1 = lv_keyboard_create(ui_ScanBandPnl3);
lv_obj_set_width( ui_Keyboard1, 300);
lv_obj_set_height( ui_Keyboard1, 120);
lv_obj_set_x( ui_Keyboard1, 5 );
lv_obj_set_y( ui_Keyboard1, 14 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

ui_SaveNewBand = lv_btn_create(ui_ScanBandPnl3);
lv_obj_set_width( ui_SaveNewBand, 100);
lv_obj_set_height( ui_SaveNewBand, 26);
lv_obj_set_x( ui_SaveNewBand, 0 );
lv_obj_set_y( ui_SaveNewBand, 99 );
lv_obj_set_align( ui_SaveNewBand, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SaveNewBand, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SaveNewBand, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_SaveNewBand);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"SAVE");

lv_obj_add_event_cb(ui_ScanBandBtn, ui_event_ScanBandBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard1,ui_BandNameTextArea);
lv_obj_add_event_cb(ui_SaveNewBand, ui_event_SaveNewBand, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RecordScreen, ui_event_RecordScreen, LV_EVENT_ALL, NULL);
uic_RecordScreen = ui_RecordScreen;
uic_ScanBandPnl1 = ui_ScanBandPnl1;
uic_ScanBandBtn = ui_ScanBandBtn;
uic_ScanBandPnl2 = ui_ScanBandPnl2;
uic_ScanBandPnl3 = ui_ScanBandPnl3;
uic_BandNameTextArea = ui_BandNameTextArea;
uic_SaveNewBand = ui_SaveNewBand;

}

void ui_RecordScreen_screen_destroy(void)
{
   if (ui_RecordScreen) lv_obj_del(ui_RecordScreen);

// NULL screen variables
uic_RecordScreen= NULL;
ui_RecordScreen= NULL;
uic_ScanBandPnl1= NULL;
ui_ScanBandPnl1= NULL;
uic_ScanBandBtn= NULL;
ui_ScanBandBtn= NULL;
ui_Label2= NULL;
uic_ScanBandPnl2= NULL;
ui_ScanBandPnl2= NULL;
ui_Colorwheel2= NULL;
ui_Button2= NULL;
ui_Label3= NULL;
uic_ScanBandPnl3= NULL;
ui_ScanBandPnl3= NULL;
uic_BandNameTextArea= NULL;
ui_BandNameTextArea= NULL;
ui_Keyboard1= NULL;
uic_SaveNewBand= NULL;
ui_SaveNewBand= NULL;
ui_Label4= NULL;

}
