// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#ifndef UI_STANDBYSCREEN_H
#define UI_STANDBYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StandbyScreen
extern void ui_StandbyScreen_screen_init(void);
extern void ui_StandbyScreen_screen_destroy(void);
extern lv_obj_t *ui_StandbyScreen;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_clock;
extern lv_obj_t *ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_StandbyScreen;
extern lv_obj_t *uic_clock;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

