// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_success = NULL;
// event funtions
void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Scanner, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Scanner_screen_init);
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_success = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_success, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_success, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_success, LV_ALIGN_CENTER );
lv_label_set_text(ui_success,"YUP!");
lv_obj_set_style_text_font(ui_success, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_success= NULL;

}
