// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#include "ui.h"

lv_obj_t *uic_clock;
lv_obj_t *uic_StandbyScreen;
lv_obj_t *ui_StandbyScreen = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_clock = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions

// build funtions

void ui_StandbyScreen_screen_init(void)
{
ui_StandbyScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_StandbyScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_StandbyScreen, lv_color_hex(0xFFF6DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StandbyScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_StandbyScreen);
lv_img_set_src(ui_Image1, &ui_img_mickey_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 216
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 216
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clock = lv_label_create(ui_StandbyScreen);
lv_obj_set_width( ui_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_clock, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock,"00:00");
lv_obj_set_style_text_color(ui_clock, lv_color_hex(0x3175A4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_clock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_clock, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_StandbyScreen);
lv_img_set_src(ui_Image2, &ui_img_white_starsbackground_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 149
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 193
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,150);

uic_StandbyScreen = ui_StandbyScreen;
uic_clock = ui_clock;

}

void ui_StandbyScreen_screen_destroy(void)
{
   if (ui_StandbyScreen) lv_obj_del(ui_StandbyScreen);

// NULL screen variables
uic_StandbyScreen= NULL;
ui_StandbyScreen= NULL;
ui_Image1= NULL;
uic_clock= NULL;
ui_clock= NULL;
ui_Image2= NULL;

}
