// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#include "ui.h"

lv_obj_t *uic_mickeyScanner;
lv_obj_t *uic_Scanner;
lv_obj_t *ui_Scanner = NULL;lv_obj_t *ui_mickeyScanner = NULL;
// event funtions
void ui_event_Scanner( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}

// build funtions

void ui_Scanner_screen_init(void)
{
ui_Scanner = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Scanner, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Scanner, lv_color_hex(0xF9F6DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Scanner, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mickeyScanner = lv_img_create(ui_Scanner);
lv_img_set_src(ui_mickeyScanner, &ui_img_mickey_png);
lv_obj_set_width( ui_mickeyScanner, LV_SIZE_CONTENT);  /// 184
lv_obj_set_height( ui_mickeyScanner, LV_SIZE_CONTENT);   /// 158
lv_obj_set_align( ui_mickeyScanner, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_mickeyScanner, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_mickeyScanner, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Scanner, ui_event_Scanner, LV_EVENT_ALL, NULL);
uic_Scanner = ui_Scanner;
uic_mickeyScanner = ui_mickeyScanner;

}

void ui_Scanner_screen_destroy(void)
{
   if (ui_Scanner) lv_obj_del(ui_Scanner);

// NULL screen variables
uic_Scanner= NULL;
ui_Scanner= NULL;
uic_mickeyScanner= NULL;
ui_mickeyScanner= NULL;

}
