// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MagicBandHub

#ifndef UI_SCANNER_H
#define UI_SCANNER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Scanner
extern void ui_Scanner_screen_init(void);
extern void ui_Scanner_screen_destroy(void);
extern void ui_event_Scanner( lv_event_t * e);
extern lv_obj_t *ui_Scanner;
extern lv_obj_t *ui_mickeyScanner;
extern lv_obj_t *ui_RegisterConfirmPnl;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_NewBandConfirm;
extern lv_obj_t *ui_Label14;
extern void ui_event_NewBandCancel( lv_event_t * e);
extern lv_obj_t *ui_NewBandCancel;
extern lv_obj_t *ui_Label15;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Scanner;
extern lv_obj_t *uic_mickeyScanner;
extern lv_obj_t *uic_RegisterConfirmPnl;
extern lv_obj_t *uic_NewBandConfirm;
extern lv_obj_t *uic_NewBandCancel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

